### ISSUE TITLE
Handling multiple scenes from the same band in one dataset object

### ISSUE THREAD

**Issue by deastwoo** [ruithnadsteud/yt_georaster#29]
If I want to compare the same band (or band ratio) from two scenes I currently cannot do this with yt.

This is a common part of a workflow. For example if I wanted to compare the NDVI values of an area over the seasons to see the growth cycle of vegetation, I would want to load multiple images covering the same area of interest at different times of the year. Currently, if I try to do this with yt.load it will be impossible to call the bands from different times. This is also an issue if I want to have multiple images from the same sensor and same time but slightly different footprints.

If there are multiple versions of the same band from the same sensor we should use other factors to allow the user to differentiate between the bands, e.g. time of acquisition, tile number field, [data level](https://earthdata.nasa.gov/collaborate/open-data-services-and-software/data-information-policy/data-levels), satellite (e.g. S2A, S2B), orbit number.

There is often a lot of information in the file name (e.g. [Sentinel 2 naming convention](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/naming-convention)) but this level of detail is not consistent for all data sources. It would be great to have yt parse all of the information but maybe a fall back would be to use the full band file name when yt can't easily differentiate between two files.

**Comment by brittonsmith** [comment]
Resolved in PR #41.
