### ISSUE TITLE
Pass desired projection at load to be used as working projection for dataset

### ISSUE THREAD

**Issue by deastwoo** [ruithnadsteud/yt_georaster#48]
Rather than purely basing the dataset's projection off the data we should add the option to pass a desired dataset CRS to reproject all the data bands to.

I think this will involve adding a keyword argument to yt.load (or maybe later in the process when we define a container?) taking a CRS string (e.g. "epsg:****") which would be readable by rasterio.

This could then be set as the dataset's crs and all bands would be reprojected as normal.

**Comment by deastwoo** [comment]
This can now be done using the crs keyword argument at load. `ds = yt.load(filename, crs="epsg:****")`

**Comment by brittonsmith** [comment]
@deastwoo we should perhaps add some documentation for this. Can you add a note in the sphinx docs about this?
