### ISSUE TITLE
Installation Error from circleci

### ISSUE THREAD

**Issue by deastwoo** [ruithnadsteud/yt_georaster#52]
I've noticed circleci is throwing an error when it tries to install pygdal 2.4.0.6

```
Collecting pygdal==2.4.0.6
  Downloading pygdal-2.4.0.6.tar.gz (447 kB)
     |████████████████████████████████| 447 kB 14.9 MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /home/circleci/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-43quxssd/pygdal_1baeab1e7ab6481bb50d969ee2dd695d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-43quxssd/pygdal_1baeab1e7ab6481bb50d969ee2dd695d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n_dzoj5r
         cwd: /tmp/pip-install-43quxssd/pygdal_1baeab1e7ab6481bb50d969ee2dd695d/
    Complete output (5 lines):
    /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_2to3_fixers'
      warnings.warn(msg)
    /usr/local/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_2to3_exclude_fixers'
      warnings.warn(msg)
    error in pygdal setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d1/e2/4fef429aa1157cf8636f3dd6a124bce66a8ff2470ee11a81b4a17084231f/pygdal-2.4.0.6.tar.gz#sha256=728d11f3ecae0cd3493cd27dab599a0b6184f5504cc172d49400d88ea2b24a9c (from https://pypi.org/simple/pygdal/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pygdal==2.4.0.6 (from versions: 1.8.1.0, 1.8.1.1, 1.8.1.2, 1.8.1.3, 1.8.1.5, 1.8.1.6, 1.9.2.0, 1.9.2.1, 1.9.2.3, 1.9.2.5, 1.9.2.6, 1.10.0.0, 1.10.0.1, 1.10.0.3, 1.10.0.5, 1.10.0.6, 1.10.1.0, 1.10.1.1, 1.10.1.3, 1.10.1.5, 1.10.1.6, 1.11.0.0, 1.11.0.1, 1.11.0.3, 1.11.0.5, 1.11.0.6, 1.11.1.0, 1.11.1.1, 1.11.1.3, 1.11.1.5, 1.11.1.6, 1.11.2.1, 1.11.2.3, 1.11.2.5, 1.11.2.6, 1.11.3.3, 1.11.3.5, 1.11.3.6, 1.11.4.3, 1.11.4.5, 1.11.4.6, 1.11.5.3, 1.11.5.5, 1.11.5.6, 2.0.0.3, 2.0.0.5, 2.0.0.6, 2.0.1.3, 2.0.1.5, 2.0.1.6, 2.0.2.3, 2.0.2.5, 2.0.2.6, 2.0.3.3, 2.0.3.5, 2.0.3.6, 2.1.0.3, 2.1.0.5, 2.1.0.6, 2.1.1.3, 2.1.1.5, 2.1.1.6, 2.1.2.3, 2.1.2.5, 2.1.2.6, 2.1.3.3, 2.1.3.5, 2.1.3.6, 2.2.0.3, 2.2.0.5, 2.2.0.6, 2.2.1.3, 2.2.1.5, 2.2.1.6, 2.2.2.3, 2.2.2.5, 2.2.2.6, 2.2.3.3, 2.2.3.5, 2.2.3.6, 2.2.4.3, 2.2.4.5, 2.2.4.6, 2.3.0.4, 2.3.0.5, 2.3.0.6, 2.3.1.4, 2.3.1.5, 2.3.1.6, 2.3.2.4, 2.3.2.5, 2.3.2.6, 2.3.3.6, 2.4.0.4, 2.4.0.5, 2.4.0.6, 2.4.1.4, 2.4.1.5, 2.4.1.6, 2.4.2.5, 2.4.2.6, 2.4.4.6, 3.0.0.5, 3.0.0.6, 3.0.1.5, 3.0.1.6, 3.0.2.6, 3.0.3.6, 3.0.4.6, 3.1.0.6, 3.1.1.6, 3.1.2.6, 3.1.3.6, 3.1.4.6, 3.2.0.6, 3.2.1.6, 3.2.1.7, 3.2.2.6, 3.2.2.7, 3.2.3.7, 3.3.0.7, 3.3.1.7)
ERROR: No matching distribution found for pygdal==2.4.0.6
```
I believe Nathan had a similar issue when trying to install. In the end he had to install using `conda develop -b .`.

Doing this might however be linked to another issue he has experienced. To avoid an import error he has to also comment out any reference to polygon selector in `data_structures.py`.

(2) After installing yt_georaster, could not import it: got this error: 
    from yt_georaster.polygon_selector import PolygonSelector
```
ModuleNotFoundError: No module named 'yt_georaster.polygon_selector'
```
Nathan's workaround was to disable the polygon selector by commenting out the following lines in `yt_georaster/yt_georaster/data_structures.py`:
```
[26]
# from yt_georaster.polygon import YTPolygon, PolygonSelector
[208-211]
# elif isinstance(selector, PolygonSelector):
#    left_edge, right_edge = selector.dobj._get_bbox()
#    left_edge = left_edge.d
#    right_edge = right_edge.d
[346]
# self.polygon = functools.partial(YTPolygon, ds=weakref.proxy(self))
```
As polygon selector is using cython and has to built from source I think the solution to both of these problems are linked, possibly through specifying a different version of gdal when installing through pip.

**Comment by deastwoo** [comment]
I had a bit of trouble installing on my mac. Finally I think I have a working list steps for installation using conda:

1. once you conda installed, create a new environment

```
conda create --name yttest
```

```
conda activate yttest
```

2. install GDAL from conda-forge

```
conda install conda-forge::gdal
```

3. install yt from source.

navigate to where you want to clone the yt and yt_georaster repos to.

```
git clone https://github.com/yt-project/yt

cd yt/

pip install -e .
```

4. `pip install cython` <-- missing dependency?

5. pip install yt_georaster from source

navigate out of your yt repo directory.

```
git clone https://github.com/ruithnadsteud/yt_georaster

cd yt_georaster/

pip install -e .
```

It would great if others could try reinstalling and see if this or another method succeeds for them. I am not sure what is causing circleci to fail.

**Comment by brittonsmith** [comment]
Sorry everyone, I am totally snowed under at the moment!

@nbourne2 the error you're seeing is yt trying to run with a different version of numpy than it was compiled with. Unfortunately, between two recent numpy versions (1.19 and 1.20, I think), this binary incompatibility crept in. Normally, it wouldn't matter much if yt was built on one version and run with another, but this has stopped it. My guess is that `intel-tensorflow` is mandating numpy < 1.20. One thing to try is to edit the `setup.py` in yt_georaster (line ~86) to 'numpy==1.19.5' to pin to a specific numpy version, then try to reinstall. There may be some subtleties to getting this right, but something of this nature should work. I've got to run now. I'm sorry to not be of more help.

**Comment by deastwoo** [comment]
Related to this I am going to push a change which should mean we don't need to worry about gdal (as much) anymore. Rasterio seems to come with gdal set up so if we remove gdal from our list of dependencies everything seems to work perfectly.

With that change I was able to install yt_georaster on my mac and on Ubuntu using the following:
```
conda create --name yt-wo-gdal python=3.8.12
conda activate yt-wo-gdal
```
These first two steps are just to set up a new `3.8.12` python environment - which seems to be the magic number, I don't think we need to use conda. Now we can just use pip install.
```
pip install yt
pip install cython
pip install -e .
```

**Comment by deastwoo** [comment]
This appears to now be resolved following a series of updates. With circleci now running successfully I will close this issue.
